# PostgreSQL
spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# リバースプロキシ対応
server.forward-headers-strategy=FRAMEWORK
